=== peterkelly/nreduce/lite_FFI/Code_Generator/DefinitionFile/nreduce_FFI.dtd
<!-- document root-->
<!ELEMENT FUNCDEF (INTERFACE+, STRUCT*)>

<!-- at least one method should be defined -->
<!ELEMENT INTERFACE (METHOD+)>
<!ATTLIST INTERFACE name NMTOKEN #REQUIRED>

<!ELEMENT METHOD (RESULT, PARAMETER*)>
<!ATTLIST METHOD name NMTOKEN  #REQUIRED>

<!ELEMENT RESULT EMPTY>
<!ATTLIST RESULT name NMTOKEN #REQUIRED type NMTOKENS #REQUIRED>

<!ELEMENT PARAMETER EMPTY>
<!ATTLIST PARAMETER name NMTOKEN #REQUIRED type NMTOKENS #REQUIRED>

<!-- user-defined c struct -->
<!ELEMENT STRUCT ((STRUCTCOM|STRUCTDEC)*)>
<!ATTLIST STRUCT type NMTOKENS #REQUIRED>

<!-- c struct declare -->
<!ELEMENT STRUCTDEC EMPTY>
<!ATTLIST STRUCTDEC name NMTOKEN #REQUIRED type NMTOKENS #REQUIRED>

<!-- c struct component, containing c types such as int, String -->
<!ELEMENT STRUCTCOM EMPTY>
<!ATTLIST STRUCTCOM name NMTOKEN #REQUIRED type NMTOKEN #REQUIRED>

=== peterkelly/nreduce/lite_FFI/Code_Generator/DefinitionFile/graphDraw.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FUNCDEF SYSTEM "nreduce_FFI.dtd">
<FUNCDEF>
    <INTERFACE name="graph">
        <METHOD name="drawRectangles">
            <RESULT name="numRect" type="int" />
            <PARAMETER name="userName" type="String" />
            <PARAMETER name="xPos" type="double" />
            <PARAMETER name="yPos" type="int" />
            <PARAMETER name="rect" type="struct Rectangle" />
        </METHOD>
        <METHOD name="enlargeRect">
            <RESULT name="rect_return" type="struct Rectangle" />
            <PARAMETER name="originalRect" type="struct Rectangle" />
            <PARAMETER name="times" type="int" />
        </METHOD>
    </INTERFACE>

    <STRUCT type="struct Rectangle">
        <STRUCTCOM name="width" type="int" />
        <STRUCTCOM name="creator" type="String" />
        <STRUCTCOM name="height" type="int" ></STRUCTCOM>
        <STRUCTDEC name="col" type="struct Color" />
    </STRUCT>

    <STRUCT type="struct Color">
        <STRUCTCOM name="red" type="int" />
        <STRUCTCOM name="blue" type="int" />
        <STRUCTCOM name="green" type="int" />
        <STRUCTDEC name="cg" type="struct gray" />
    </STRUCT>
    
    <STRUCT type="struct gray">
        <STRUCTCOM name="country" type="String" />
        <STRUCTCOM name="grayCode" type="int" /></STRUCT>

</FUNCDEF>

=== peterkelly/nreduce/lite_FFI/Code_Generator/DefinitionFile/zziplib.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FUNCDEF SYSTEM "nreduce_FFI.dtd">
<FUNCDEF>
	<INTERFACE name="zzip">
		<METHOD name="readFile">
			<RESULT name ="content" type="String" ></RESULT>
			<PARAMETER name="fileName" type="String"></PARAMETER>
			<PARAMETER name="length" type="int" />
		</METHOD>
		<METHOD name="getFileInfo">
			<RESULT name="content" type="struct_FileInfo" ></RESULT>
			<PARAMETER name="fileName" type="String" />
		</METHOD>
		<METHOD name="getNumChar">
			<RESULT name="numChar" type="int" ></RESULT>
		</METHOD>
	</INTERFACE>
	<STRUCT name="struct_FileInfo">
		<CTYPE type="String" ></CTYPE>
		<CTYPE type="String" />
		<CTYPE type="String" />
	</STRUCT>
</FUNCDEF>

=== peterkelly/nreduce/lite_FFI/Code_Generator/DefinitionFile/ImageMagick.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FUNCDEF SYSTEM "nreduce_FFI.dtd">
<FUNCDEF>
    <INTERFACE name="imagemagick">
        <METHOD name="magickResizeImage">
            <RESULT name="result" type="int" />
            <PARAMETER name="imageFile" type="String" />
            <PARAMETER name="outputImage" type="String" />
            <PARAMETER name="columns" type="int" />
            <PARAMETER name="rows" type="int" />
            <PARAMETER name="magickFilter" type="int" ></PARAMETER>
            <PARAMETER name="blur" type="double" />
        </METHOD>
        
        <METHOD name="magickRotateImage">
            <RESULT name="result" type="int" />
            <PARAMETER name="imageFile" type="String" />
            <PARAMETER name="outputImage" type="String" />
            <PARAMETER name="degree" type="double" />
        </METHOD>
        
        <METHOD name="magickChopImage">
            <RESULT name="result" type="int" />
            <PARAMETER name="imageFile" type="String" />
            <PARAMETER name="outputImage" type="String" />
            <PARAMETER name="width" type="int" />
            <PARAMETER name="height" type="int" />
            <PARAMETER name="xPos" type="int" />
            <PARAMETER name="yPos" type="int" ></PARAMETER>
        </METHOD>
        
        <METHOD name="magickCompressImage">
            <RESULT name="result" type="int" />
            <PARAMETER name="imageFile" type="String" />
            <PARAMETER name="outputImage" type="String" />
            <PARAMETER name="format" type="String" />
            <PARAMETER name="compressionType" type="int" />
            <PARAMETER name="compressionRate" type="double" />
        </METHOD>
        
        <METHOD name="magickUnsharpMaskImage">
            <RESULT name="result" type="int" />
            <PARAMETER name="imageFile" type="String" />
            <PARAMETER name="outputImage" type="String" />
            <PARAMETER name="radius" type="double" />
            <PARAMETER name="sigma" type="double" />
            <PARAMETER name="amount" type="double" />
            <PARAMETER name="threshold" type="double" />
        </METHOD>
        
        <METHOD name="magickThumbnailImage">
            <RESULT name="result" type="int" ></RESULT>
            <PARAMETER name="imageFile" type="String" />
            <PARAMETER name="outputImage" type="String" />
            <PARAMETER name="columns" type="int" />
            <PARAMETER name="rows" type="int" />
        </METHOD>
        
        <METHOD name="magickMotionBlurImage">
            <RESULT name="result" type="int" />
            <PARAMETER name="imageFile" type="String" />
            <PARAMETER name="outputImage" type="String" />
            <PARAMETER name="radius" type="double" />
            <PARAMETER name="sigma" type="double" />
            <PARAMETER name="angle" type="double" />
        </METHOD>

        <METHOD name="magickModulateImage">
            <RESULT name="result" type="int" />
            <PARAMETER name="imageFile" type="String" />
            <PARAMETER name="outputImage" type="String" />
            <PARAMETER name="brightness" type="double" />
            <PARAMETER name="saturation" type="double" />
            <PARAMETER name="hue" type="double" />
        </METHOD>
    </INTERFACE>
</FUNCDEF>
